import discord
from discord.ext import commands
from colorama import Fore
import asyncio
from webserver import keep_alive
import os


prefix = "$$"

keep_alive()

bot = commands.Bot(command_prefix=prefix,
                   help_command=None,
                   case_insensitive=True,
                   self_bot=True)

@bot.event
async def on_ready():
    await bot.change_presence(status=discord.Status.offline)
    print("Bot is ready!")




@bot.command()
async def helpowo(ctx):
    await asyncio.sleep(1)
    await ctx.message.delete()
    await ctx.send('**$$AutoOwO= owoh, owo b, owo sell all, owo flip 600. $$stopautoOwO= Stops the bot. bybasses ban**')

@bot.command()
async def stopautoOwO(ctx):
    await ctx.message.delete()
    await ctx.send('**AutoOwO is now Disabled 😊**')
    global dmcs
    dmcs = False


@bot.command(pass_context=True)
async def autoOwO(ctx):
    await ctx.message.delete()
    await ctx.send('**AutoOwO is now enabled enjoy 😊**')
    global dmcs
    dmcs = True
    while dmcs:
        async with ctx.typing():
            await asyncio.sleep(3)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo flip 600')
            await asyncio.sleep(2)
            ctx.send('owo sell all')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo sell all')
            await asyncio.sleep(2)
            ctx.send('owo flip 800')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo flip 600')
            await asyncio.sleep(2)
            ctx.send('owo sell all')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo sell all')
            await asyncio.sleep(2)
            ctx.send('owo flip 800')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo flip 600')
            await asyncio.sleep(2)
            ctx.send('owo sell all')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo sell all')
            await asyncio.sleep(2)
            ctx.send('owo flip 800')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo flip 600')
            await asyncio.sleep(2)
            ctx.send('owo sell all')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo sell all')
            await asyncio.sleep(2)
            ctx.send('owo flip 800')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo flip 600')
            await asyncio.sleep(2)
            ctx.send('owo sell all')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo sell all')
            await asyncio.sleep(2)
            ctx.send('owo flip 800')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo flip 600')
            await asyncio.sleep(2)
            ctx.send('owo sell all')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo sell all')
            await asyncio.sleep(2)
            ctx.send('owo flip 800')
            print('Break for 30 mins')
            await asyncio.sleep(1800)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo flip 600')
            await asyncio.sleep(2)
            ctx.send('owo sell all')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo sell all')
            await asyncio.sleep(2)
            ctx.send('owo flip 800')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo flip 600')
            await asyncio.sleep(2)
            ctx.send('owo sell all')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo sell all')
            await asyncio.sleep(2)
            ctx.send('owo flip 800')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo flip 600')
            await asyncio.sleep(2)
            ctx.send('owo sell all')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo sell all')
            await asyncio.sleep(2)
            ctx.send('owo flip 800')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo flip 600')
            await asyncio.sleep(2)
            ctx.send('owo sell all')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo sell all')
            await asyncio.sleep(2)
            ctx.send('owo flip 800')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo flip 600')
            await asyncio.sleep(2)
            ctx.send('owo sell all')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo sell all')
            await asyncio.sleep(2)
            ctx.send('owo flip 800')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo flip 600')
            await asyncio.sleep(2)
            ctx.send('owo sell all')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo sell all')
            await asyncio.sleep(2)
            ctx.send('owo flip 800')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo flip 600')
            await asyncio.sleep(2)
            ctx.send('owo sell all')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo sell all')
            await asyncio.sleep(2)
            ctx.send('owo flip 800')
            print('break for 45 mins')
            await asyncio.sleep(2700)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo flip 600')
            await asyncio.sleep(2)
            ctx.send('owo sell all')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo sell all')
            await asyncio.sleep(2)
            ctx.send('owo flip 800')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo flip 600')
            await asyncio.sleep(2)
            ctx.send('owo sell all')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo sell all')
            await asyncio.sleep(2)
            ctx.send('owo flip 800')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo flip 600')
            await asyncio.sleep(2)
            ctx.send('owo sell all')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo sell all')
            await asyncio.sleep(2)
            ctx.send('owo flip 800')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo flip 600')
            await asyncio.sleep(2)
            ctx.send('owo sell all')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo sell all')
            await asyncio.sleep(2)
            ctx.send('owo flip 800')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo flip 600')
            await asyncio.sleep(2)
            ctx.send('owo sell all')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo sell all')
            await asyncio.sleep(2)
            ctx.send('owo flip 800')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo flip 600')
            await asyncio.sleep(2)
            ctx.send('owo sell all')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo sell all')
            await asyncio.sleep(2)
            ctx.send('owo flip 800')
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo flip 600')
            await asyncio.sleep(2)
            ctx.send('owo sell all')
            await asyncio.sleep(16)
            ctx.send('oh')
            await asyncio.sleep(2)
            ctx.send('ob')
            await asyncio.sleep(4)
            ctx.send('owo sell all')
            await asyncio.sleep(2)
            ctx.send('owo flip 800')
            await asyncio.sleep(16)
            print('Break For 2 hour')
            await asyncio.sleep(7200)



            

            




bot.run(os.getenv('token'), bot=False)
