import discord
from discord.ext import commands
from colorama import Fore
import asyncio
from webserver import keep_alive
import os


prefix = "$$"

keep_alive()

bot = commands.Bot(command_prefix=prefix,
                   help_command=None,
                   case_insensitive=True,
                   self_bot=True)





@bot.command()
async def help(ctx):
    await ctx.message.delete()
    await ctx.send('**$$AutoOwO= owoh, owo b, owo sell all, owo flip 600. $$stopautoOwO= Stops the bot. bybasses ban**')

@bot.command()
async def stopautoOwO(ctx):
    await ctx.message.delete()
    await ctx.send('**AutoOwO is now Disabled 😊**')
    global dmcs
    dmcs = False


@bot.command(pass_context=True)
async def autoOwO(ctx):
    await ctx.message.delete()
    await ctx.send('**AutoOwO is now enabled enjoy 😊**')
    global dmcs
    dmcs = True
    while dmcs:
        async with ctx.typing():
            await asyncio.sleep(3)
            await ctx.send('owo h')
            print(f"{Fore.GREEN} Succesfully sent owo h")
            await asyncio.sleep(2)
            await ctx.send('owo b')
            print(f"{Fore.GREEN} Succesfully sent owo b")
            await asyncio.sleep(5)
            await ctx.send('owo flip 600')
            print(f"{Fore.GREEN} Succesfully sent owo flip 600")
            await asyncio.sleep(14)
            await ctx.send('owo h')
            print(f"{Fore.GREEN} Succesfully sent owo h")
            await asyncio.sleep(2)
            await ctx.send('owo b')
            print(f"{Fore.GREEN} Succesfully sent owo b")
            await asyncio.sleep(5)
            await ctx.send('owo flip 600')
            print(f"{Fore.GREEN} Succesfully sent owo flip 600")
            await asyncio.sleep(14)
            await ctx.send('owo h')
            print(f"{Fore.GREEN} Succesfully sent owo h")
            await asyncio.sleep(2)
            await ctx.send('owo b')
            print(f"{Fore.GREEN} Succesfully sent owo b")
            await asyncio.sleep(5)
            await ctx.send('owo flip 600')
            print(f"{Fore.GREEN} Succesfully sent owo flip 600")
            await asyncio.sleep(14)
            await ctx.send('owo h')
            print(f"{Fore.GREEN} Succesfully sent owo h")
            await asyncio.sleep(2)
            await ctx.send('owo b')
            print(f"{Fore.GREEN} Succesfully sent owo b")
            await asyncio.sleep(5)
            await ctx.send('owo flip 600')
            print(f"{Fore.GREEN} Succesfully sent owo flip 600")
            await asyncio.sleep(14)
            await ctx.send('owo h')
            print(f"{Fore.GREEN} Succesfully sent owo h")
            await asyncio.sleep(2)
            await ctx.send('owo b')
            print(f"{Fore.GREEN} Succesfully sent owo b")
            await asyncio.sleep(5)
            await ctx.send('owo flip 600')
            print(f"{Fore.GREEN} Succesfully sent owo flip 600")
            await asyncio.sleep(14)
            await ctx.send('owo h')
            print(f"{Fore.GREEN} Succesfully sent owo h")
            await asyncio.sleep(2)
            await ctx.send('owo b')
            print(f"{Fore.GREEN} Succesfully sent owo b")
            await asyncio.sleep(5)
            await ctx.send('owo flip 600')
            print(f"{Fore.GREEN} Succesfully sent owo flip 600")
            await asyncio.sleep(14)
            await ctx.send('owo h')
            print(f"{Fore.GREEN} Succesfully sent owo h")
            await asyncio.sleep(2)
            await ctx.send('owo b')
            print(f"{Fore.GREEN} Succesfully sent owo b")
            await asyncio.sleep(5)
            await ctx.send('owo flip 600')
            print(f"{Fore.GREEN} Succesfully sent owo flip 600")
            await asyncio.sleep(14)
            await ctx.send('owo h')
            print(f"{Fore.GREEN} Succesfully sent owo h")
            await asyncio.sleep(2)
            await ctx.send('owo b')
            print(f"{Fore.GREEN} Succesfully sent owo b")
            await asyncio.sleep(5)
            await ctx.send('owo flip 600')
            print(f"{Fore.GREEN} Succesfully sent owo flip 600")
            print(f"{Fore.GREEN} Took a break for 30 mins")
            await asyncio.sleep(1800)
            await ctx.send('owo h')
            print(f"{Fore.GREEN} Succesfully sent owo h")
            await asyncio.sleep(2)
            await ctx.send('owo b')
            print(f"{Fore.GREEN} Succesfully sent owo b")
            await asyncio.sleep(5)
            await ctx.send('owo flip 600')
            print(f"{Fore.GREEN} Succesfully sent owo flip 600")
            await asyncio.sleep(14)
            await ctx.send('owo h')
            print(f"{Fore.GREEN} Succesfully sent owo h")
            await asyncio.sleep(2)
            await ctx.send('owo b')
            print(f"{Fore.GREEN} Succesfully sent owo b")
            await asyncio.sleep(5)
            await ctx.send('owo flip 600')
            print(f"{Fore.GREEN} Succesfully sent owo flip 600")
            await asyncio.sleep(14)
            await ctx.send('owo h')
            print(f"{Fore.GREEN} Succesfully sent owo h")
            await asyncio.sleep(2)
            await ctx.send('owo b')
            print(f"{Fore.GREEN} Succesfully sent owo b")
            await asyncio.sleep(5)
            await ctx.send('owo flip 600')
            print(f"{Fore.GREEN} Succesfully sent owo flip 600")
            await asyncio.sleep(14)
            await ctx.send('owo h')
            print(f"{Fore.GREEN} Succesfully sent owo h")
            await asyncio.sleep(2)
            await ctx.send('owo b')
            print(f"{Fore.GREEN} Succesfully sent owo b")
            await asyncio.sleep(5)
            await ctx.send('owo flip 600')
            print(f"{Fore.GREEN} Succesfully sent owo flip 600")
            await asyncio.sleep(14)
            await ctx.send('owo h')
            print(f"{Fore.GREEN} Succesfully sent owo h")
            await asyncio.sleep(2)
            await ctx.send('owo b')
            print(f"{Fore.GREEN} Succesfully sent owo b")
            await asyncio.sleep(5)
            await ctx.send('owo flip 600')
            print(f"{Fore.GREEN} Succesfully sent owo flip 600")
            await asyncio.sleep(14)
            await ctx.send('owo h')
            print(f"{Fore.GREEN} Succesfully sent owo h")
            await asyncio.sleep(2)
            await ctx.send('owo b')
            print(f"{Fore.GREEN} Succesfully sent owo b")
            await asyncio.sleep(5)
            await ctx.send('owo flip 600')
            print(f"{Fore.GREEN} Succesfully sent owo flip 600")
            await asyncio.sleep(14)
            await ctx.send('owo h')
            print(f"{Fore.GREEN} Succesfully sent owo h")
            await asyncio.sleep(2)
            await ctx.send('owo b')
            print(f"{Fore.GREEN} Succesfully sent owo b")
            await asyncio.sleep(5)
            await ctx.send('owo flip 600')
            print(f"{Fore.GREEN} Succesfully sent owo flip 600")
            await asyncio.sleep(14)
            await ctx.send('owo h')
            print(f"{Fore.GREEN} Succesfully sent owo h")
            await asyncio.sleep(2)
            await ctx.send('owo b')
            print(f"{Fore.GREEN} Succesfully sent owo b")
            await asyncio.sleep(5)
            await ctx.send('owo flip 600')
            print(f"{Fore.GREEN} Succesfully sent owo flip 600")
            await asyncio.sleep(14)
            await ctx.send('owo h')
            print(f"{Fore.GREEN} Succesfully sent owo h")
            await asyncio.sleep(2)
            await ctx.send('owo b')
            print(f"{Fore.GREEN} Succesfully sent owo b")
            await asyncio.sleep(5)
            await ctx.send('owo flip 600')
            print(f"{Fore.GREEN} Succesfully sent owo flip 600")
            await asyncio.sleep(14)
            await ctx.send('owo h')
            print(f"{Fore.GREEN} Succesfully sent owo h")
            await asyncio.sleep(2)
            await ctx.send('owo b')
            print(f"{Fore.GREEN} Succesfully sent owo b")
            await asyncio.sleep(5)
            await ctx.send('owo flip 600')
            print(f"{Fore.GREEN} Succesfully sent owo flip 600")
            print(f"{Fore.GREEN} Took break for an hour")
            await asyncio.sleep(3600)
            await ctx.send('owo h')
            print(f"{Fore.GREEN} Succesfully sent owo h")
            await asyncio.sleep(2)
            await ctx.send('owo b')
            print(f"{Fore.GREEN} Succesfully sent owo b")
            await asyncio.sleep(5)
            await ctx.send('owo flip 600')
            print(f"{Fore.GREEN} Succesfully sent owo flip 600")
            await asyncio.sleep(14)
            await ctx.send('owo h')
            print(f"{Fore.GREEN} Succesfully sent owo h")
            await asyncio.sleep(2)
            await ctx.send('owo b')
            print(f"{Fore.GREEN} Succesfully sent owo b")
            await asyncio.sleep(5)
            await ctx.send('owo flip 600')
            print(f"{Fore.GREEN} Succesfully sent owo flip 600")
            await asyncio.sleep(14)
            await ctx.send('owo h')
            print(f"{Fore.GREEN} Succesfully sent owo h")
            await asyncio.sleep(2)
            await ctx.send('owo b')
            print(f"{Fore.GREEN} Succesfully sent owo b")
            await asyncio.sleep(5)
            await ctx.send('owo flip 600')
            print(f"{Fore.GREEN} Succesfully sent owo flip 600")
            await asyncio.sleep(14)
            await ctx.send('owo h')
            print(f"{Fore.GREEN} Succesfully sent owo h")
            await asyncio.sleep(2)
            await ctx.send('owo b')
            print(f"{Fore.GREEN} Succesfully sent owo b")
            await asyncio.sleep(5)
            await ctx.send('owo flip 600')
            print(f"{Fore.GREEN} Succesfully sent owo flip 600")
            await asyncio.sleep(14)
            await ctx.send('owo h')
            print(f"{Fore.GREEN} Succesfully sent owo h")
            await asyncio.sleep(2)
            await ctx.send('owo b')
            print(f"{Fore.GREEN} Succesfully sent owo b")
            await asyncio.sleep(5)
            await ctx.send('owo flip 600')
            print(f"{Fore.GREEN} Succesfully sent owo flip 600")
            await asyncio.sleep(14)
            await ctx.send('owo h')
            print(f"{Fore.GREEN} Succesfully sent owo h")
            await asyncio.sleep(2)
            await ctx.send('owo b')
            print(f"{Fore.GREEN} Succesfully sent owo b")
            await asyncio.sleep(5)
            await ctx.send('owo flip 600')
            print(f"{Fore.GREEN} Succesfully sent owo flip 600")
            await asyncio.sleep(14)
            await ctx.send('owo h')
            print(f"{Fore.GREEN} Succesfully sent owo h")
            await asyncio.sleep(2)
            await ctx.send('owo b')
            print(f"{Fore.GREEN} Succesfully sent owo b")
            await asyncio.sleep(5)
            await ctx.send('owo flip 600')
            print(f"{Fore.GREEN} Succesfully sent owo flip 600")
            await asyncio.sleep(14)
            await ctx.send('owo h')
            print(f"{Fore.GREEN} Succesfully sent owo h")
            await asyncio.sleep(2)
            await ctx.send('owo b')
            print(f"{Fore.GREEN} Succesfully sent owo b")
            await asyncio.sleep(5)
            await ctx.send('owo flip 600')
            print(f"{Fore.GREEN} Succesfully sent owo flip 600")
            await asyncio.sleep(14)
            await ctx.send('owo h')
            print(f"{Fore.GREEN} Succesfully sent owo h")
            await asyncio.sleep(2)
            await ctx.send('owo b')
            print(f"{Fore.GREEN} Succesfully sent owo b")
            await asyncio.sleep(5)
            await ctx.send('owo flip 600')
            print(f"{Fore.GREEN} Succesfully sent owo flip 600")
            await asyncio.sleep(14)
            await ctx.send('owo h')
            print(f"{Fore.GREEN} Succesfully sent owo h")
            await asyncio.sleep(2)
            await ctx.send('owo b')
            print(f"{Fore.GREEN} Succesfully sent owo b")
            await asyncio.sleep(5)
            await ctx.send('owo flip 600')
            print(f"{Fore.GREEN} Succesfully sent owo flip 600")
            await asyncio.sleep(1800)

            




bot.run(os.getenv('token'), bot=False)
